---
- name: update p1 and s nodes
  hosts: cws_nodes,z1_*
  gather_facts: false
  vars_prompt:
    - name: EMAIL
      prompt: "what is your ftp3 username"
      private: no

    - name: PW
      prompt: "what is your ftp3 password"
      private: yes
  roles:
    - { role: z1_role, tags: ['z1'] }
