---
# handlers file for roles/z1_role

- name: createrepo_itops_redhat7
  shell:
    chdir: "{{ RH7_ITOPS_REPO }}"
    cmd: createrepo .
  when: inventory_hostname in groups['z1_reposync_nodes']

- name: createrepo_redhat6
  shell:
    chdir: "{{ RH6_REPO }}"
    cmd: createrepo .
  when: inventory_hostname in groups['z1_reposync_nodes']
